apiVersion: v1
kind: Service
metadata:
  name: moocozin-shoes-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: moocozin-shoes
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
